feign:
  hystrix:
#    enabled: true #开启Hystrix
  #对请求与响应进行GZIP压缩
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
###################################################
hystrix:
  threadpool:
    default:
      coreSize: 1000 #缺省为10
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 80000
          strategy: SEMAPHORE

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eager-load:
    enabled: true
    clients: DLMS--dlms-file-zhengwei20
########################################################
spring:
  cloud:
    refresh:
      refreshable: none
  messages:
    basename: messages
lmp:
  service:
    enabled: false

################################################################
#mybatis配置
mybatis-plus:
  type-aliases-package: com.lenovo.bigdata.delivery.dlms.demo.dao.mapper
  mapper-locations: classpath:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
  global-config:
    banner: false

###################################################################3
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
